import type { Component } from 'vue'
import {
  IconApps,
  IconBarChart,
  IconBook,
  IconBranch,
  IconBug,
  IconCalendar,
  IconCheckSquare,
  IconCode,
  IconCommon,
  IconCompass,
  IconComputer,
  IconCopy,
  IconDashboard,
  IconDesktop,
  IconDownload,
  IconDragArrow,
  IconEdit,
  IconEmail,
  IconFile,
  IconFilter,
  IconFullscreen,
  IconFullscreenExit,
  IconGithub,
  IconHistory,
  IconIdcard,
  IconLanguage,
  IconLink,
  IconList,
  IconLock,
  IconMenu,
  IconMessage,
  IconMindMapping,
  IconNotification,
  IconPalette,
  IconQuestion,
  IconRecord,
  IconSafe,
  IconSchedule,
  IconSearch,
  IconSelectAll,
  IconSettings,
  IconSkin,
  IconStar,
  IconStorage,
  IconSwap,
  IconTool,
  IconUpload,
  IconUser,
  IconUserGroup,
  IconWechat
} from '@arco-design/web-vue/es/icon'

/**
 * 若依图标短名（及 Arco 图标名）-> Arco 图标组件映射：
 * - AppIcon 渲染与 IconSelect 图标选择器共用本映射，保证可选项都能正确渲染
 * - 支持若依图标短名（system/monitor/tool/...）与直接 Arco 图标名（如 IconSettings）
 */
export const APP_ICON_MAP: Record<string, Component> = {
  // 系统与监控
  system: IconSettings,
  monitor: IconDesktop,
  server: IconComputer,
  druid: IconStorage,
  redis: IconStorage,
  'redis-list': IconList,
  bug: IconBug,
  dashboard: IconDashboard,
  online: IconUserGroup,
  logininfor: IconRecord,
  operlog: IconHistory,
  job: IconSchedule,
  // 开发与工具
  tool: IconTool,
  build: IconBranch,
  swagger: IconBook,
  form: IconEdit,
  gen: IconCode,
  code: IconCode,
  html: IconCode,
  config: IconTool,
  dict: IconBook,
  drag: IconDragArrow,
  // 用户与组织
  user: IconUser,
  people: IconUser,
  peoples: IconUserGroup,
  role: IconUserGroup,
  menu: IconMenu,
  dept: IconMindMapping,
  post: IconIdcard,
  education: IconBook,
  password: IconLock,
  // 日志与消息
  log: IconFile,
  message: IconMessage,
  notice: IconNotification,
  email: IconEmail,
  logininforalt: IconRecord,
  // 通用示例
  guide: IconCompass,
  example: IconApps,
  demo: IconApps,
  component: IconApps,
  tab: IconApps,
  chart: IconBarChart,
  nested: IconBranch,
  tree: IconMindMapping,
  'tree-table': IconMindMapping,
  list: IconList,
  table: IconList,
  number: IconList,
  documentation: IconFile,
  text: IconFile,
  excel: IconFile,
  date: IconCalendar,
  time: IconHistory,
  // 系统功能图标
  fullscreen: IconFullscreen,
  exitfullscreen: IconFullscreenExit,
  github: IconGithub,
  icon: IconStar,
  star: IconStar,
  rate: IconStar,
  international: IconLanguage,
  language: IconLanguage,
  link: IconLink,
  lock: IconLock,
  money: IconSafe,
  validCode: IconSafe,
  question: IconQuestion,
  search: IconSearch,
  select: IconSelectAll,
  skin: IconSkin,
  theme: IconSkin,
  color: IconPalette,
  upload: IconUpload,
  download: IconDownload,
  wechat: IconWechat,
  clipboard: IconCopy,
  edit: IconEdit,
  input: IconEdit,
  textarea: IconEdit,
  cascade: IconBranch,
  checkbox: IconCheckSquare,
  radio: IconRecord,
  slider: IconFilter,
  switch: IconSwap,
  kb: IconCommon,
  // 直接使用 Arco 图标名（如 IconSettings -> IconSettings）
  IconSettings,
  IconDesktop,
  IconComputer,
  IconStorage,
  IconList,
  IconBug,
  IconDashboard,
  IconUserGroup,
  IconRecord,
  IconHistory,
  IconSchedule,
  IconTool,
  IconBranch,
  IconBook,
  IconEdit,
  IconCode,
  IconUser,
  IconMenu,
  IconMindMapping,
  IconIdcard,
  IconFile,
  IconMessage,
  IconNotification,
  IconEmail,
  IconCompass,
  IconApps,
  IconBarChart,
  IconCalendar,
  IconFullscreen,
  IconFullscreenExit,
  IconGithub,
  IconStar,
  IconLanguage,
  IconLink,
  IconLock,
  IconSafe,
  IconQuestion,
  IconSearch,
  IconSelectAll,
  IconSkin,
  IconUpload,
  IconDownload,
  IconWechat,
  IconCopy,
  IconPalette,
  IconDragArrow,
  IconCheckSquare,
  IconFilter,
  IconSwap,
  IconCommon
}

/** 图标选择器可选项（短名优先的平铺列表） */
export const APP_ICON_NAMES: string[] = Object.keys(APP_ICON_MAP)
